export const sites = {
  tide: {
    name: "Tide & Marine Conditions",
    canonicalHost: "tide99.com",
    analyticsId: "G-SWVLQ1LFZ7",
    eyebrow: "US tide & marine conditions",
    icon: "≈",
    accent: "#00d4c8",
    dark: "#062d38",
    pale: "#e8fbf8",
    promise: "Plan around the water, not around a generic forecast.",
    description:
      "Official NOAA high and low tide predictions with recent water-level observations, datum, units and station status kept visible.",
    search: "Search a NOAA station or coastal place",
    entity: "station",
    count: "214 prediction stations",
    sources: [
      {
        name: "NOAA CO-OPS Data API",
        licence: "US federal government data",
        url: "https://api.tidesandcurrents.noaa.gov/api/dev",
      },
    ],
    projection: "public-projections/tide-marine/catalog.json",
    status: "projection-pending",
    examples: [
      "Next high and low tide",
      "Observed level versus prediction",
      "Datum and local-time explanation",
      "Station coverage and freshness",
    ],
  },
  asic: {
    name: "AustralianCompanyData",
    canonicalHost: "australiancompanydata.com",
    analyticsId: "G-SWVLQ1LFZ7",
    eyebrow: "Verified ASIC company register",
    icon: "AU",
    accent: "#ffb000",
    dark: "#251a08",
    pale: "#fff7df",
    promise: "A clearer view of official Australian company identity.",
    description:
      "Look up a company by exact ACN and understand status, registration history, company type and official source context.",
    search: "Exact Australian Company Number (ACN)",
    entity: "company",
    count: "4,002,072 unique ACNs",
    sources: [
      {
        name: "ASIC Current Company Dataset",
        licence: "CC BY 3.0 Australia",
        url: "https://data.gov.au/data/dataset/asic-companies",
      },
    ],
    projection: "public-projections/australiancompanydata/catalog.json",
    status: "projection-pending",
    examples: [
      "Current company status",
      "Registration and deregistration dates",
      "Current and former names",
      "Entity type, class and subclass",
    ],
  },
  charity: {
    name: "CharitySignal",
    canonicalHost: "charitysignal.co.uk",
    analyticsId: "G-SWVLQ1LFZ7",
    eyebrow: "England & Wales charity register",
    icon: "CS",
    accent: "#8c5cff",
    dark: "#21133d",
    pale: "#f3efff",
    promise:
      "Official charity facts, filings and purpose in one evidence view.",
    description:
      "Organisation-only Charity Commission records, designed to explain status, purposes, operating areas and annual-return history without publishing trustee or private contact data.",
    search: "Charity name or registration number",
    entity: "charity",
    count: "398,112 organisation records",
    sources: [
      {
        name: "Charity Commission Full Register",
        licence: "Open Government Licence v3.0",
        url: "https://register-of-charities.charitycommission.gov.uk/en/register/full-register-download",
      },
    ],
    projection: "public-projections/charitysignal/catalog.json",
    status: "projection-pending",
    examples: [
      "Registration and reporting status",
      "Income and expenditure history",
      "Purposes and classifications",
      "Operating areas and filing dates",
    ],
  },
  boat: {
    name: "BoatSafetyCheck",
    canonicalHost: "boatrecallcheck.com",
    analyticsId: "G-SWVLQ1LFZ7",
    eyebrow: "US recreational boat safety evidence",
    icon: "⚓",
    accent: "#ff7a45",
    dark: "#102d3a",
    pale: "#eef8fa",
    promise:
      "Check the equipment approval and recall trail before you cast off.",
    description:
      "A planned USCG evidence tool for approved equipment, boat recalls and manufacturer/model matching. It remains closed until the exact source releases, licences and public fields are verified live.",
    search: "Approval number, manufacturer or boat model",
    entity: "marine safety record",
    count: "source verification in progress",
    sources: [],
    projection: "public-projections/boat-safety/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "USCG approval and equipment identity",
      "Boat and model recall matching",
      "Remedy and owner-action summaries",
      "Source dates, limits and official links",
    ],
  },
  fcc: {
    name: "FCC Equipment ID Lookup",
    canonicalHost: "fccidcheck.com",
    analyticsId: "G-SWVLQ1LFZ7",
    eyebrow: "Small, fast equipment-authorisation experiment",
    icon: "FCC",
    accent: "#ffd84d",
    dark: "#161f3d",
    pale: "#f2f5ff",
    promise: "Turn an FCC ID into a clear authorisation trail.",
    description:
      "A deliberately narrow equipment-grant lookup. Existing browser-harvested FCC files remain quarantined; the public experiment opens only after an owner-direct source and safe field projection are proven.",
    search: "FCC ID, grantee code or equipment class",
    entity: "equipment authorisation",
    count: "experiment gated",
    sources: [],
    projection: "public-projections/fcc-equipment/catalog.json",
    status: "projection-pending",
    examples: [
      "FCC ID and grant identity",
      "Equipment class and authorisation date",
      "Grantee organisation without private addresses",
      "Official filing and exhibits links",
    ],
  },
  vehicleimport: {
    name: "Vehicle Import Eligibility Checker",
    canonicalHost: "vehicleimportfacts.com",
    analyticsId: "G-SWVLQ1LFZ7",
    eyebrow: "Focused cross-border vehicle evidence",
    icon: "↔",
    accent: "#a7f35a",
    dark: "#18311f",
    pale: "#f2faed",
    promise:
      "Check the corridor, vehicle facts and official rules before you ship.",
    description:
      "A corridor-first decision tool joining approved NHTSA, DVSA, RDW, NZ Fleet, Traficom and Canadian vehicle evidence. It will not claim legal eligibility from incomplete model matching.",
    search: "Select an origin, destination and vehicle",
    entity: "vehicle/corridor check",
    count: "corridor source pack incomplete",
    sources: [],
    projection: "public-projections/vehicle-import/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Origin-to-destination rule checklist",
      "Model, fuel and emissions evidence",
      "Recall and compliance context",
      "Official next steps and unresolved checks",
    ],
  },
  rates: {
    name: "HomeRate UK",
    eyebrow: "Interest rates & housing costs",
    icon: "%",
    accent: "#ff5e7d",
    dark: "#35101a",
    pale: "#fff0f3",
    promise: "Turn rate changes into an honest household-cost picture.",
    description:
      "A future UK evidence tool joining official rate history, mortgage illustrations, housing prices, earnings and inflation—without pretending a generic estimate is personal financial advice.",
    search: "Explore a UK area or rate scenario",
    entity: "area",
    count: "source pack incomplete",
    sources: [],
    projection: "public-projections/rates-housing/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Rate timeline with effective dates",
      "Illustrative payment scenarios",
      "Local price-to-earnings context",
      "Method, assumptions and limitations",
    ],
  },
  snow: {
    name: "AlpineSignal CH",
    eyebrow: "Swiss avalanche & snow conditions",
    icon: "△",
    accent: "#66b7ff",
    dark: "#0a253b",
    pale: "#edf7ff",
    promise:
      "Swiss mountain evidence with danger, elevation and freshness intact.",
    description:
      "A Switzerland-only launch concept for official avalanche bulletins, danger regions, snow observations and station context. It will not imply safety or create pages beyond actual coverage.",
    search: "Search a Swiss region or station",
    entity: "region",
    count: "source pack incomplete",
    sources: [
      {
        name: "SLF Avalanche Bulletins",
        licence: "Swiss Open Government Data terms",
        url: "https://www.slf.ch/en/avalanche-bulletin-and-snow-situation/",
      },
    ],
    projection: "public-projections/swiss-avalanche/catalog.json",
    status: "projection-pending",
    examples: [
      "Official danger level and bulletin time",
      "Elevation-specific snow observations",
      "Region coverage and uncertainty",
      "Direct link to official safety guidance",
    ],
  },
  energy: {
    name: "LabelLogic",
    eyebrow: "Energy label decoder",
    icon: "A",
    accent: "#89d329",
    dark: "#16310b",
    pale: "#f2fae8",
    promise: "Understand the label before comparing the product.",
    description:
      "Scheme-specific energy-label evidence for UK, EU and Australia, keeping classifications, test methods, dates and jurisdictional differences separate.",
    search: "Product model or label identifier",
    entity: "product",
    count: "scheme projections incomplete",
    sources: [],
    projection: "public-projections/energy-labels/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Label class in the correct scheme",
      "Annual energy and declared capacity",
      "Comparable products under one test method",
      "Scheme version and effective date",
    ],
  },
  river: {
    name: "FloodingFacts",
    canonicalHost: "floodingfacts.com",
    analyticsId: "G-SWVLQ1LFZ7",
    eyebrow: "Live river readings & flood warnings",
    icon: "↟",
    accent: "#2fc4ff",
    dark: "#082d42",
    pale: "#eaf9ff",
    promise: "See what the river is doing—and how fresh the reading is.",
    description:
      "Environment Agency stations, measures, latest readings, areas and warnings, with thresholds and missing-data states kept explicit.",
    search: "River, station or nearby place",
    entity: "station",
    count: "5,523 stations · 7,361 measures",
    sources: [
      {
        name: "Environment Agency Flood Monitoring API",
        licence: "Open Government Licence v3.0",
        url: "https://environment.data.gov.uk/flood-monitoring/doc/reference",
      },
    ],
    projection: "public-projections/floodingfacts/catalog.json",
    status: "projection-pending",
    examples: [
      "Latest level and observation time",
      "Typical range and threshold context",
      "Current official warnings",
      "Catchment, station and measure coverage",
    ],
  },
  roads: {
    name: "PlaceChecker",
    canonicalHost: "placechecker.co.uk",
    analyticsId: "G-SWVLQ1LFZ7",
    eyebrow: "Bounded local road-safety evidence",
    icon: "!",
    accent: "#ff784f",
    dark: "#35140a",
    pale: "#fff2ed",
    promise:
      "Find patterns in collisions without turning incidents into clickbait.",
    description:
      "DfT STATS19 collision aggregates by bounded road and area, joined to defensible traffic and population denominators before rates or rankings are shown.",
    search: "Road, local authority or area",
    entity: "area",
    count: "2021–2025 collision corpus",
    sources: [
      {
        name: "DfT Road Safety Open Data",
        licence: "Open Government Licence v3.0",
        url: "https://www.gov.uk/government/statistical-data-sets/road-safety-open-data",
      },
    ],
    projection: "public-projections/road-collisions/catalog.json",
    status: "projection-pending",
    examples: [
      "Collision counts by severity",
      "Road, light and weather context",
      "Comparable rates with denominators",
      "Method and historical-data warning",
    ],
  },
  heritage: {
    name: "Listed Building Facts",
    canonicalHost: "listedbuildingfacts.com",
    analyticsId: "G-SWVLQ1LFZ7",
    eyebrow: "UK heritage atlas",
    icon: "H",
    accent: "#d6a866",
    dark: "#332719",
    pale: "#faf4e9",
    promise: "Understand why a place is listed, protected and significant.",
    description:
      "A named listed-building and designated-place atlas built around official identity, mapped context and evidence-rich relationships—not generic tourism summaries.",
    search: "Monument, listed place or area",
    entity: "heritage place",
    count: "entity qualification pending",
    sources: [],
    projection: "public-projections/heritage-atlas/catalog.json",
    status: "projection-pending",
    examples: [
      "Official designation and identifier",
      "Map, boundary and nearby context",
      "Designation timeline and evidence",
      "Related monuments and landscape",
    ],
  },
  cosmetics: {
    name: "INCI Plain",
    eyebrow: "UK cosmetics ingredient decoder",
    icon: "i",
    accent: "#ff82ad",
    dark: "#3d1324",
    pale: "#fff0f5",
    promise: "Turn an ingredient list into evidence—not a fear score.",
    description:
      "Decode standard INCI names, functions, synonyms and regulatory context while separating official classifications from editorial explanation.",
    search: "Ingredient or INCI name",
    entity: "ingredient",
    count: "projection qualification pending",
    sources: [],
    projection: "public-projections/cosmetics-inci/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Standard INCI identity",
      "Function and formulation role",
      "Regulatory context by jurisdiction",
      "Synonyms and evidence sources",
    ],
  },
  facilities: {
    name: "CivicNear US",
    eyebrow: "US public facilities directory",
    icon: "US",
    accent: "#4aa3ff",
    dark: "#102747",
    pale: "#edf5ff",
    promise: "Official public facilities, joined around the place you need.",
    description:
      "A facility-level US directory only where official identifiers, useful service fields and local long-tail demand beat generic head-term directories.",
    search: "Facility, service or US place",
    entity: "facility",
    count: "facility projections incomplete",
    sources: [],
    projection: "public-projections/us-public-facilities/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Official facility identity",
      "Services and operating authority",
      "Mapped access and nearby context",
      "Coverage and update dates",
    ],
  },
  wildlife: {
    name: "WildNear",
    eyebrow: "nearby wildlife finder",
    icon: "W",
    accent: "#64b66e",
    dark: "#17351d",
    pale: "#eff8f0",
    promise:
      "Discover what was recorded nearby—without claiming it always lives there.",
    description:
      "Occurrence evidence with dates, repetition, source and precision safeguards. Sensitive species locations are obscured or excluded.",
    search: "Species or place",
    entity: "occurrence area",
    count: "geo-index projection incomplete",
    sources: [],
    projection: "public-projections/wildlife-nearby/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Recent and historic observations",
      "Repeated versus one-off records",
      "Safe mapped range context",
      "Seasonality and evidence coverage",
    ],
  },
  prop65: {
    name: "WarningContext CA",
    eyebrow: "California Prop 65 decoder",
    icon: "65",
    accent: "#ffd447",
    dark: "#392d07",
    pale: "#fff9dd",
    promise:
      "Understand the chemical and warning—without pretending to assess your exposure.",
    description:
      "Official California listed-chemical identities, listing basis, dates and warning context with clear legal and health-information limitations.",
    search: "Chemical or warning term",
    entity: "chemical",
    count: "official projection incomplete",
    sources: [],
    projection: "public-projections/prop65/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Official listed name and synonyms",
      "Listing date and basis",
      "Warning-category context",
      "Authoritative source links",
    ],
  },
  cycling: {
    name: "CityCycle Live",
    eyebrow: "urban cycling & bike share",
    icon: "↗",
    accent: "#34d399",
    dark: "#0b3327",
    pale: "#eafbf5",
    promise: "See the network that actually exists in each city.",
    description:
      "City editions for bike-share stations, route networks and public cycling infrastructure; no empty global pages beyond verified coverage.",
    search: "City, station or cycling route",
    entity: "city or station",
    count: "city-edition projections incomplete",
    sources: [],
    projection: "public-projections/urban-cycling/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Live station availability where licensed",
      "Network and route coverage",
      "Nearby public facilities",
      "City-specific source freshness",
    ],
  },
  grocery: {
    name: "BasketEvidence",
    eyebrow: "everyday grocery prices",
    icon: "B",
    accent: "#ff8a3d",
    dark: "#3b1d09",
    pale: "#fff3e9",
    promise: "Track a real basket, not a headline built from two prices.",
    description:
      "A product and basket history tool that stays closed until identity matching, retailer coverage, comparable units and repeated licensed snapshots are sufficient.",
    search: "Product or basket",
    entity: "product",
    count: "repeat-snapshot pack incomplete",
    sources: [],
    projection: "public-projections/grocery-prices/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Exact product and pack identity",
      "Comparable unit price",
      "Retailer coverage",
      "Real snapshot history",
    ],
  },
  books: {
    name: "OpenShelf Classics",
    eyebrow: "public-domain library",
    icon: "O",
    accent: "#bc8cff",
    dark: "#2d1741",
    pale: "#f7efff",
    promise:
      "Explore public-domain books through evidence-rich editions and themes.",
    description:
      "A held-back library concept: only rights-cleared texts and metadata, with edition provenance and useful thematic joins rather than copied title pages.",
    search: "Author, title or theme",
    entity: "work",
    count: "held outside immediate portfolio scope",
    sources: [],
    projection: "public-projections/open-library/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Work and edition identity",
      "Public-domain basis by jurisdiction",
      "Themes and related works",
      "Source edition and downloadable formats",
    ],
  },
  repair: {
    name: "RepairLens",
    eyebrow: "module-first repairability evidence",
    icon: "R",
    accent: "#40c9a2",
    dark: "#0e352c",
    pale: "#eafaf6",
    promise:
      "See what makes a product repairable—and what the score leaves out.",
    description:
      "A module-first evidence product for official repairability schemes, parts, support periods and methodology. It should integrate with product pages before earning a domain.",
    search: "Product model",
    entity: "product",
    count: "module qualification pending",
    sources: [],
    projection: "public-projections/product-repairability/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Official score and scheme version",
      "Parts and documentation factors",
      "Support-period evidence",
      "Comparable models",
    ],
  },
  car: {
    name: "ModelYear Reliability",
    eyebrow: "ModelYearFacts reliability module",
    icon: "MY",
    accent: "#93a5ff",
    dark: "#18214d",
    pale: "#f0f2ff",
    promise:
      "Compare model years from recalls, tests and MOT evidence—not anecdotes.",
    description:
      "A module-first join for official recall and MOT failure evidence with identity confidence, denominators and test-period caveats.",
    search: "Make, model and year",
    entity: "model year",
    count: "module join incomplete",
    sources: [],
    projection: "public-projections/modelyear-reliability/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Recall history",
      "MOT failure categories",
      "Model-year comparison",
      "Coverage and denominator caveats",
    ],
  },
  beach: {
    name: "SwimSignal",
    eyebrow: "beach & bathing-water safety",
    icon: "~",
    accent: "#1ec8ff",
    dark: "#07334a",
    pale: "#e8faff",
    promise: "Check official bathing-water evidence before you swim.",
    description:
      "Country-specific official classifications, sampling history, warnings and amenity context with seasonal and geographic coverage made explicit.",
    search: "Beach or bathing water",
    entity: "bathing water",
    count: "country projections incomplete",
    sources: [],
    projection: "public-projections/bathing-water/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Current official classification",
      "Sampling and warning history",
      "Season and coverage dates",
      "Nearby access and facilities",
    ],
  },
  ev: {
    name: "EV Shift",
    eyebrow: "EV adoption & registrations",
    icon: "EV",
    accent: "#b2ef42",
    dark: "#243508",
    pale: "#f5fde8",
    promise: "Track where electric vehicles are actually entering the fleet.",
    description:
      "Official aggregate registrations, fleet share and charging context by compatible geography and period, without mixing schemes or incompatible snapshots.",
    search: "Country, region or vehicle class",
    entity: "area",
    count: "registration projections incomplete",
    sources: [],
    projection: "public-projections/ev-adoption/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "EV registrations and fleet share",
      "Change across real periods",
      "Vehicle-class composition",
      "Charging context and coverage",
    ],
  },
  tender: {
    name: "TenderTenderTender",
    canonicalHost: "tendertendertender.com",
    analyticsId: "G-SWVLQ1LFZ7",
    eyebrow: "UK public procurement history",
    icon: "T",
    accent: "#ffd84d",
    dark: "#272008",
    pale: "#fffbea",
    promise: "Follow public contracts through buyers, categories and dates.",
    description:
      "Contracts Finder notice and buyer history from an approved organisation-only projection. Supplier history remains closed until a legal-entity-only projection passes the privacy gate.",
    search: "OCID or public buyer",
    entity: "contract notice",
    count: "142 governed notices",
    sources: [
      {
        name: "Contracts Finder",
        licence: "Open Government Licence v3.0 for covered Crown content",
        url: "https://www.contractsfinder.service.gov.uk/",
      },
    ],
    projection: "public-projections/tendertendertender/catalog.json",
    status: "projection-pending",
    examples: [
      "Buyer notice history",
      "Contract dates and values",
      "Procurement category history",
      "Official notice links",
    ],
  },
  ukmoney: {
    name: "UK Public Money",
    eyebrow: "Supporting procurement evidence",
    icon: "£",
    accent: "#63d6a0",
    dark: "#0d3022",
    pale: "#ecfbf4",
    promise: "Connect public spending questions to dated procurement notices.",
    description:
      "Contracts Finder is used as supporting procurement evidence alongside the site's established public-money sources; it is not treated as a complete spending ledger.",
    search: "OCID or public buyer",
    entity: "procurement notice",
    count: "142 supporting notices",
    sources: [
      {
        name: "Contracts Finder",
        licence: "Open Government Licence v3.0 for covered Crown content",
        url: "https://www.contractsfinder.service.gov.uk/",
      },
    ],
    projection: "public-projections/ukpublicmoney/catalog.json",
    status: "projection-pending",
    examples: [
      "Buyer procurement activity",
      "Published contract values",
      "Category and timing context",
      "Links to official notices",
    ],
  },
  climatecontext: {
    name: "Climate99",
    eyebrow: "Climate evidence context",
    icon: "C",
    accent: "#f6a84b",
    dark: "#34200b",
    pale: "#fff6e8",
    promise: "Add climate context without turning observations into forecasts.",
    description:
      "Climate99 provides observational context for Tide, FloodingFacts and PlaceChecker. Each downstream module retains geography, observation period, completeness and source.",
    search: "Place, station or indicator",
    entity: "climate evidence",
    count: "supporting module",
    sources: [
      {
        name: "NOAA GHCN",
        licence: "US federal government data",
        url: "https://www.ncei.noaa.gov/products/land-based-station/global-historical-climatology-network-daily",
      },
    ],
    projection: "public-projections/climate99/catalog.json",
    status: "source-pack-incomplete",
    examples: [
      "Station record context",
      "Long-run normals",
      "Completeness and observation period",
      "Links to Tide, FloodingFacts and PlaceChecker",
    ],
  },
};
